[package]
name = "lib_hello"
version = "0.1.0"
authors = ["Roc Thompson <roc.gui@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
